"""Adicionado usuario e relacionamentos

Revision ID: e5e3a8ff1807
Revises: 9450e3692016
Create Date: 2026-02-19 10:34:13.689519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5e3a8ff1807'
down_revision: Union[str, Sequence[str], None] = '9450e3692016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    # Produtos: add column only if missing
    prod_cols = [r[1] for r in conn.execute(sa.text("PRAGMA table_info('produtos')")).fetchall()]
    if 'usuario_id' not in prod_cols:
        op.add_column('produtos', sa.Column('usuario_id', sa.Integer(), nullable=True))

    # create FK on produtos only if not present
    prod_fks = conn.execute(sa.text("PRAGMA foreign_key_list('produtos')")).fetchall()
    if not any(r[3] == 'usuario_id' and r[2] == 'usuarios' for r in prod_fks):
        from alembic import op as _op
        with _op.batch_alter_table('produtos') as batch_op:
            batch_op.create_foreign_key('fk_produtos_usuario_id', 'usuarios', ['usuario_id'], ['id'])

    # Usuarios: add columns only if missing
    user_cols = [r[1] for r in conn.execute(sa.text("PRAGMA table_info('usuarios')")).fetchall()]
    if 'senha' not in user_cols:
        op.add_column('usuarios', sa.Column('senha', sa.String(), nullable=True))
    if 'usuario_id' not in user_cols:
        op.add_column('usuarios', sa.Column('usuario_id', sa.Integer(), nullable=True))

    # create self-referencing FK on usuarios only if not present
    user_fks = conn.execute(sa.text("PRAGMA foreign_key_list('usuarios')")).fetchall()
    if not any(r[3] == 'usuario_id' and r[2] == 'usuarios' for r in user_fks):
        from alembic import op as _op
        with _op.batch_alter_table('usuarios') as batch_op:
            batch_op.create_foreign_key('fk_usuarios_usuario_id', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # use batch mode for dropping constraints on SQLite
    from alembic import op as _op
    with _op.batch_alter_table('usuarios') as batch_op:
        batch_op.drop_constraint('fk_usuarios_usuario_id', type_='foreignkey')
    op.drop_column('usuarios', 'usuario_id')
    op.drop_column('usuarios', 'senha')

    with _op.batch_alter_table('produtos') as batch_op:
        batch_op.drop_constraint('fk_produtos_usuario_id', type_='foreignkey')
    op.drop_column('produtos', 'usuario_id')
    # ### end Alembic commands ###
